mono

diff --git a/.github/workflows/functions-test-all.yaml b/.github/workflows/functions-test-all.yaml
--- a/.github/workflows/functions-test-all.yaml
+++ b/.github/workflows/functions-test-all.yaml
@@ -160,78 +160,78 @@ jobs:
           pip install --upgrade pip
           pip install -r requirements.txt
       # Build the marketplace documentation
-#      - name: Build marketplace docs
-#      # Set the branch name as an environment variable
-#        env:
-#          CHANNEL: ${{ steps.branch.outputs.branch }}
-#      # pull the latest changes from the marketplace repo, run the build-marketplace script from the functions repo
-#        run: |
-#          cd marketplace
-#          pwd
-#          git pull origin
-#          cd ..
-#          python functions/functions/functions.py build-marketplace -s functions -m marketplace -c $CHANNEL -v -f
-#      # Publish the marketplace release - push the changes to the marketplace repo
-#      - name: Publish marketplace release
-#        env:
-#          GITHUB_TOKEN: ${{ secrets.MARKETPLACE_ACCESS_TOKEN_V3 }}
-#          USERNAME: iguazio-cicd
-#          USEREMAIL: iguaziocicd@gmail.com
-#          REPO_PATH: marketplace
-#          BASE_REPO: mlrun
-#          BASE_BRANCH: master
-#        # The following script do the followings:
-#        # 1. checkout the marketplace directory
-#        # 2. generate a commit SHA and save the changes into a variable named `COMMIT_SHA`
-#        # 3. generate a branch name based on the commit SHA - marketplace-doc-gen-$COMMIT_SHA
-#        # 4. merge base branch (master) into the new branch
-#        # 5. add all the changes to the new branch, and a commit is made with a message that includes the commit SHA
-#        # 6. push the changes to the marketplace repo
-#        # 7. create a pull request from the new branch to the base branch
-#        run: |
-#          cd marketplace
-#          pwd
-#          COMMIT_SHA=$(git rev-parse --short "$GITHUB_SHA")
-#          echo "commit sha: $COMMIT_SHA"
-#          echo "github sha: $GITHUB_SHA"
-#          BRANCH_NAME=marketplace-doc-gen-$COMMIT_SHA
-#          REMOTE=https://$USERNAME:$GITHUB_TOKEN@github.com/$BASE_REPO/$REPO_PATH.git
-#          echo "Validating environment params...";
-#          [ -z "${GITHUB_TOKEN}" ] && {
-#              echo 'Missing input "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}".';
-#              exit 1;
-#          };
-#          git config --local user.name $USERNAME
-#          git config --local user.email $USEREMAIL
-#          git branch --set-upstream-to origin/master
-#          git remote -v
-#          echo "1. Checking out [$BRANCH_NAME]..."
-#          git checkout -b $BRANCH_NAME
-#          echo "2. Checking out [$BASE_BRANCH]..."
-#          git checkout $BASE_BRANCH
-#          git pull
-#          echo "3. Checking out [$BRANCH_NAME]..."
-#          git checkout $BRANCH_NAME
-#          echo "3a. merging"
-#          git merge $BASE_BRANCH
-#          echo "3b. status"
-#          git status
-#          git status --ignored
-#          find . -type f | xargs ls -artl
-#          echo "3b. add"
-#          git add --all
-#          git status
-#          git status --ignored
-#          echo "4. Commiting changes..."
-#          echo "4a. git rev-parse"
-#          git rev-parse --show-toplevel
-#          echo "4b. git commit"
-#          git commit -a -m "Automatically generated by github-worflow[bot] for commit: $COMMIT_SHA"
-#          git status
-#          git status --ignored
-#          # https://stackoverflow.com/questions/64270867/auth-error-trying-to-copy-a-repo-with-github-actions
-#          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
-#          echo "Pushing [$BRANCH_NAME] to remote [$REMOTE]"
-#          git push -f $REMOTE $BRANCH_NAME
-#          echo "Submiting pull request..."
-#          gh pr create --title "Marketplace update from $BRANCH_NAME" --body "github-workflow" --base $BASE_BRANCH --head $BRANCH_NAME --repo $BASE_REPO/$REPO_PATH
+      - name: Build marketplace docs
+      # Set the branch name as an environment variable
+        env:
+          CHANNEL: ${{ steps.branch.outputs.branch }}
+      # pull the latest changes from the marketplace repo, run the build-marketplace script from the functions repo
+        run: |
+          cd marketplace
+          pwd
+          git pull origin
+          cd ..
+          python functions/functions/functions.py build-marketplace -s functions -m marketplace -c $CHANNEL -v -f
+      # Publish the marketplace release - push the changes to the marketplace repo
+      - name: Publish marketplace release
+        env:
+          GITHUB_TOKEN: ${{ secrets.MARKETPLACE_ACCESS_TOKEN_V3 }}
+          USERNAME: Eyal-Danieli
+          USEREMAIL: eyald@iguazio.com
+          REPO_PATH: marketplace
+          BASE_REPO: Eyal-Danieli
+          BASE_BRANCH: monorepo
+        # The following script do the followings:
+        # 1. checkout the marketplace directory
+        # 2. generate a commit SHA and save the changes into a variable named `COMMIT_SHA`
+        # 3. generate a branch name based on the commit SHA - marketplace-doc-gen-$COMMIT_SHA
+        # 4. merge base branch (master) into the new branch
+        # 5. add all the changes to the new branch, and a commit is made with a message that includes the commit SHA
+        # 6. push the changes to the marketplace repo
+        # 7. create a pull request from the new branch to the base branch
+        run: |
+          cd marketplace
+          pwd
+          COMMIT_SHA=$(git rev-parse --short "$GITHUB_SHA")
+          echo "commit sha: $COMMIT_SHA"
+          echo "github sha: $GITHUB_SHA"
+          BRANCH_NAME=marketplace-doc-gen-$COMMIT_SHA
+          REMOTE=https://$USERNAME:$GITHUB_TOKEN@github.com/$BASE_REPO/$REPO_PATH.git
+          echo "Validating environment params...";
+          [ -z "${GITHUB_TOKEN}" ] && {
+              echo 'Missing input "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}".';
+              exit 1;
+          };
+          git config --local user.name $USERNAME
+          git config --local user.email $USEREMAIL
+          git branch --set-upstream-to origin/master
+          git remote -v
+          echo "1. Checking out [$BRANCH_NAME]..."
+          git checkout -b $BRANCH_NAME
+          echo "2. Checking out [$BASE_BRANCH]..."
+          git checkout $BASE_BRANCH
+          git pull
+          echo "3. Checking out [$BRANCH_NAME]..."
+          git checkout $BRANCH_NAME
+          echo "3a. merging"
+          git merge $BASE_BRANCH
+          echo "3b. status"
+          git status
+          git status --ignored
+          find . -type f | xargs ls -artl
+          echo "3b. add"
+          git add --all
+          git status
+          git status --ignored
+          echo "4. Commiting changes..."
+          echo "4a. git rev-parse"
+          git rev-parse --show-toplevel
+          echo "4b. git commit"
+          git commit -a -m "Automatically generated by github-worflow[bot] for commit: $COMMIT_SHA"
+          git status
+          git status --ignored
+          # https://stackoverflow.com/questions/64270867/auth-error-trying-to-copy-a-repo-with-github-actions
+          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
+          echo "Pushing [$BRANCH_NAME] to remote [$REMOTE]"
+          git push -f $REMOTE $BRANCH_NAME
+          echo "Submiting pull request..."
+          gh pr create --title "Marketplace update from $BRANCH_NAME" --body "github-workflow" --base $BASE_BRANCH --head $BRANCH_NAME --repo $BASE_REPO/$REPO_PATH
